LABEL_IDX_TO_NAME = {
    # -------------------------
    # 1.1 Daily Actions
    # -------------------------
    0: "drink water",
    1: "eat meal",
    2: "brush teeth",
    3: "brush hair",
    4: "drop",
    5: "pick up",
    6: "throw",
    7: "sit down",
    8: "stand up",
    9: "clapping",
    10: "reading",
    11: "writing",
    12: "tear up paper",
    13: "put on jacket",
    14: "take off jacket",
    15: "put on a shoe",
    16: "take off a shoe",
    17: "put on glasses",
    18: "take off glasses",
    19: "put on a hat or cap",
    20: "take off a hat or cap",
    21: "cheer up",
    22: "hand waving",
    23: "kicking something",
    24: "reach into pocket",
    25: "hopping",
    26: "jump up",
    27: "phone call",
    28: "play with phone or tablet",
    29: "type on a keyboard",
    30: "point to something",
    31: "taking a selfie",
    32: "check time from watch",
    33: "rub two hands",
    34: "nod head or bow",
    35: "shake head",
    36: "wipe face",
    37: "salute",
    38: "put palms together",
    39: "cross hands in front",

    60: "put on headphone",
    61: "take off headphone",
    62: "shoot at basket",
    63: "bounce ball",
    64: "tennis bat swing",
    65: "juggle table tennis ball",
    66: "hush",
    67: "flick hair",
    68: "thumb up",
    69: "thumb down",
    70: "make OK sign",
    71: "make victory sign",
    72: "staple book",
    73: "counting money",
    74: "cutting nails",
    75: "cutting paper",
    76: "snap fingers",
    77: "open bottle",
    78: "sniff or smell",
    79: "squat down",
    80: "toss a coin",
    81: "fold paper",
    82: "ball up paper",
    83: "play magic cube",
    84: "apply cream on face",
    85: "apply cream on hand",
    86: "put on bag",
    87: "take off bag",
    88: "put object into bag",
    89: "take object out of bag",
    90: "open a box",
    91: "move heavy objects",
    92: "shake fist",
    93: "throw up cap or hat",
    94: "capitulate",
    95: "cross arms",
    96: "arm circles",
    97: "arm swings",
    98: "run on the spot",
    99: "butt kicks",
    100: "cross toe touch",
    101: "side kick",

    # -------------------------
    # 1.2 Medical Conditions
    # -------------------------
    40: "sneeze or cough",
    41: "staggering",
    42: "falling down",
    43: "headache",
    44: "chest pain",
    45: "back pain",
    46: "neck pain",
    47: "nausea or vomiting",
    48: "fan self",
    102: "yawn",
    103: "stretch oneself",
    104: "blow nose",

    # -------------------------
    # 1.3 Mutual Actions / Two Person Interactions
    # -------------------------
    49: "punch or slap",
    50: "kicking",
    51: "pushing",
    52: "pat on back",
    53: "point finger",
    54: "hugging",
    55: "giving object",
    56: "touch pocket",
    57: "shaking hands",
    58: "walking towards",
    59: "walking apart",
    105: "hit with object",
    106: "wield knife",
    107: "knock over",
    108: "grab stuff",
    109: "shoot with gun",
    110: "step on foot",
    111: "high five",
    112: "cheers and drink",
    113: "carry object",
    114: "take a photo",
    115: "follow",
    116: "whisper",
    117: "exchange things",
    118: "support somebody",
    119: "rock paper scissors",
}
